### ISSUE TITLE
asyncio.run 开启的额外事件循环导致测试无法正常退出

### ISSUE THREAD

**Issue by StarHeartHunt** [FDCraft/nonebot-plugin-orangejuice#1]
https://github.com/FDCraft/nonebot-plugin-orangejuice/blob/c1743bbf395ec1f9bd521de0e4ff9951cf1b74be/nonebot_plugin_orangejuice/Card.py#L168

https://github.com/FDCraft/nonebot-plugin-orangejuice/blob/c1743bbf395ec1f9bd521de0e4ff9951cf1b74be/nonebot_plugin_orangejuice/Stats.py#L256

以上两处建议换用 `on_startup`，例如：
```python
from nonebot import get_driver

driver = get_driver()

@driver.on_startup
async def do_something():
    await Card().get_data()
```

**Comment by GLDYM** [comment]
![ed989d0bf674ee9a3fa623eb9026fe75](https://github.com/FDCraft/nonebot-plugin-orangejuice/assets/49135577/f9933363-30cb-4c91-a997-eca639bec56a)
# I'm baka
